create table if not exists public.local_visibility_profiles (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  gbp_score integer not null check (gbp_score between 0 and 100),
  gbp_verification_status text not null check (gbp_verification_status in ('Verified', 'Needs Verification', 'Suspended', 'Not Claimed')),
  gbp_primary_category text not null,
  gbp_additional_categories text[] not null default '{}',
  gbp_profile_completeness integer not null check (gbp_profile_completeness between 0 and 100),
  gbp_nap_consistency integer not null check (gbp_nap_consistency between 0 and 100),
  gbp_review_rating numeric(3, 2) not null check (gbp_review_rating between 0 and 5),
  gbp_review_count integer not null default 0 check (gbp_review_count >= 0),
  gbp_review_velocity_30d integer not null default 0,
  gbp_unanswered_reviews integer not null default 0 check (gbp_unanswered_reviews >= 0),
  gbp_photo_freshness_days integer not null default 0 check (gbp_photo_freshness_days >= 0),
  gbp_post_freshness_days integer not null default 0 check (gbp_post_freshness_days >= 0),
  gbp_services_completeness integer not null check (gbp_services_completeness between 0 and 100),
  gbp_product_completeness integer not null check (gbp_product_completeness between 0 and 100),
  gbp_qna_completeness integer not null check (gbp_qna_completeness between 0 and 100),
  gbp_local_pack_position integer not null check (gbp_local_pack_position > 0),
  gbp_maps_visibility_score integer not null check (gbp_maps_visibility_score between 0 and 100),
  gbp_top_issues text[] not null default '{}',
  local_seo_score integer not null check (local_seo_score between 0 and 100),
  local_nap_consistency integer not null check (local_nap_consistency between 0 and 100),
  local_citation_coverage integer not null check (local_citation_coverage between 0 and 100),
  local_location_pages_healthy integer not null default 0 check (local_location_pages_healthy >= 0),
  local_location_pages_total integer not null default 0 check (local_location_pages_total >= 0),
  local_schema_coverage integer not null check (local_schema_coverage between 0 and 100),
  local_keyword_top_10 integer not null default 0 check (local_keyword_top_10 >= 0),
  local_keyword_tracked integer not null default 0 check (local_keyword_tracked >= 0),
  local_pack_share integer not null check (local_pack_share between 0 and 100),
  local_proximity_coverage integer not null check (local_proximity_coverage between 0 and 100),
  local_top_issues text[] not null default '{}',
  aeo_score integer not null check (aeo_score between 0 and 100),
  aeo_question_led_headings integer not null default 0 check (aeo_question_led_headings >= 0),
  aeo_faq_schema_coverage integer not null check (aeo_faq_schema_coverage between 0 and 100),
  aeo_paa_coverage integer not null check (aeo_paa_coverage between 0 and 100),
  aeo_concise_answer_blocks integer not null default 0 check (aeo_concise_answer_blocks >= 0),
  aeo_voice_search_readiness integer not null check (aeo_voice_search_readiness between 0 and 100),
  aeo_source_clarity integer not null check (aeo_source_clarity between 0 and 100),
  aeo_top_issues text[] not null default '{}',
  geo_score integer not null check (geo_score between 0 and 100),
  geo_entity_coverage integer not null check (geo_entity_coverage between 0 and 100),
  geo_citation_authority integer not null check (geo_citation_authority between 0 and 100),
  geo_llm_answer_presence integer not null check (geo_llm_answer_presence between 0 and 100),
  geo_ai_overview_eligibility integer not null check (geo_ai_overview_eligibility between 0 and 100),
  geo_author_expertise_coverage integer not null check (geo_author_expertise_coverage between 0 and 100),
  geo_content_freshness integer not null check (geo_content_freshness between 0 and 100),
  geo_structured_evidence_coverage integer not null check (geo_structured_evidence_coverage between 0 and 100),
  geo_top_issues text[] not null default '{}',
  measured_at timestamptz not null default now(),
  unique (workspace_id, measured_at)
);

create index if not exists idx_local_visibility_profiles_workspace_id_measured_at
  on public.local_visibility_profiles(workspace_id, measured_at desc);
